// types.js
const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';
const SET_USER_SESSION = 'SET_USER_SESSION';

const REQUEST_SUBREDDIT_JSON = 'REQUEST_SUBREDDIT_JSON';
const RECEIVE_SUBREDDIT_JSON = 'RECEIVE_SUBREDDIT_JSON';

export default {
    INCREMENT_COUNT,
    DECREMENT_COUNT,
    REQUEST_SUBREDDIT_JSON,
    RECEIVE_SUBREDDIT_JSON,
    SET_USER_SESSION
}