const HANDLE_FIELD_CHANGE = 'HANDLE_FIELD_CHANGE';
const SET_USER_SESSION = 'SET_USER_SESSION';
const HANDLE_LOGIN_ERRORS = 'HANDLE_LOGIN_ERRORS';
const SHOW_LOADING = 'SEND_LOGIN_DATA';

export default {
    HANDLE_FIELD_CHANGE,
    SET_USER_SESSION,
    HANDLE_LOGIN_ERRORS,
    SHOW_LOADING
}