const CART_INIT_CART_DISPLAY = 'CART_INIT_CART_DISPLAY';
const CART_CLEAR_CART = 'CART_CLEAR_CART';
const CART_UPDATE_ITEMQTY = 'CART_UPDATE_ITEMQTY';
const CART_MOVE_ITEM_TO_FAV = 'CART_MOVE_ITEM_TO_FAV';
const CART_MOVE_ITEM_TO_CART = 'CART_MOVE_ITEM_TO_CART';
const CART_REMOVE_ITEM_FROM_CART = 'CART_REMOVE_ITEM_FROM_CART';
const CART_EXECUTE_CHECKOUT = 'CART_EXECUTE_CHECKOUT';
const CART_CLEAR_CART_TOBUY = 'CART_CLEAR_CART_TOBUY';
const CART_CLEAR_CART_NOT_TOBUY = 'CART_CLEAR_CART_NOT_TOBUY';

export default {
    CART_INIT_CART_DISPLAY,
    CART_CLEAR_CART,
    CART_UPDATE_ITEMQTY,
    CART_MOVE_ITEM_TO_FAV,
    CART_MOVE_ITEM_TO_CART,
    CART_REMOVE_ITEM_FROM_CART,
    CART_EXECUTE_CHECKOUT,
    CART_CLEAR_CART_TOBUY,
    CART_CLEAR_CART_NOT_TOBUY
} 