const CATS_LOADCATS = 'CATS_LOADCATS';
const CATS_SELECTCAT = 'CATS_SELECTCAT';
const CATS_UNSELECTCAT = 'CATS_UNSELECTCAT';

export default {
    CATS_LOADCATS,
    CATS_SELECTCAT,
    CATS_UNSELECTCAT
} 