const CATS_LOADCATS = 'CATS_LOADCATS';
const CATS_SELECTCAT = 'CATS_SELECTCAT';
const CATS_UNSELECTCAT = 'CATS_UNSELECTCAT';
const CATS_TOGGLECAT = 'CATS_TOGGLECAT';

export default {
    CATS_LOADCATS,
    CATS_SELECTCAT,
    CATS_UNSELECTCAT,
    CATS_TOGGLECAT
} 