const SHOP_INITSHOP = 'SHOP_INITSHOP';
const SHOP_PRODUCTLIKE = 'SHOP_PRODUCTLIKE';
const SHOP_PRODUCTBUY = 'SHOP_PRODUCTBUY';
const SHOP_PRODUCTPASS = 'SHOP_PRODUCTPASS';
const CART_UPDATE_ITEMQTY = 'CART_UPDATE_ITEMQTY';
const CART_MOVE_ITEM_TO_FAV = 'CART_MOVE_ITEM_TO_FAV';
const CART_MOVE_ITEM_TO_CART = 'CART_MOVE_ITEM_TO_CART';
const CART_REMOVE_ITEM_FROM_CART = 'CART_REMOVE_ITEM_FROM_CART';

export default {
    SHOP_INITSHOP,
    SHOP_PRODUCTLIKE,
    SHOP_PRODUCTBUY,
    SHOP_PRODUCTPASS,
    CART_UPDATE_ITEMQTY,
    CART_MOVE_ITEM_TO_FAV,
    CART_MOVE_ITEM_TO_CART,
    CART_REMOVE_ITEM_FROM_CART,
} 