const SHOP_INITSHOP = 'SHOP_INITSHOP';
const SHOP_PRODUCTLIKE = 'SHOP_PRODUCTLIKE';
const SHOP_PRODUCTBUY = 'SHOP_PRODUCTBUY';
const SHOP_PRODUCTPASS = 'SHOP_PRODUCTPASS';

export default {
    SHOP_INITSHOP,
    SHOP_PRODUCTLIKE,
    SHOP_PRODUCTBUY,
    SHOP_PRODUCTPASS
} 